/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.5.1/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    application
    alias(libs.plugins.spring.boot)
}

repositories {
    mavenCentral()
}

dependencies {
    implementation(libs.spring.boot.starter.web)
    implementation(libs.spring.boot.starter.data.jpa)
    implementation("org.springframework.security:spring-security-crypto:6.2.5")
    implementation(libs.postgresql.driver)
    testImplementation(libs.junit)
    testImplementation("org.seleniumhq.selenium:selenium-java:4.22.0")
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    mainClass = "org.example.Application"
}

tasks.bootRun {
    systemProperties = mapOf("spring.profiles.active" to "dev")
}
